### ISSUE TITLE
Ideas for observer construction and comparison

### ISSUE THREAD

**Issue by georgesbarron** [GTorlai/Observers.jl#4]
This is a really neat package, I'm looking forward to using it in my projects! Here are a couple ideas:

1. I would imagine a common use of this would be to put it into existing code to try to debug something (e.g. a numerical optimizer). In this case, instead of writing something like `Observer(["Error" => err_from_π, "Iteration" => iteration])`, it may be faster to do something like `Observer([err_from_π, iteration])`, which produces an observer equivalent to `Observer(["err_from_π" => err_from_π, "iteration" => iteration])`. If you have a lot of quantities you're interested in, it would be less tedious than copying and pasting the variable name into a string (though obviously this is not always desired).

2. Another thought would be to have some way of comparing observers. For instance, say I run some optimization and I want to compare how the observed quantities change as a function of some hyperparameter. The simplest thing I could think of would be something like making it so that you can easily look at how the values recorded in each observer compare, e.g. by difference, relative difference, etc. I don't know what this would look like more concretely, though.

**Comment by mtfishman** [comment]
Note that for you comment 2., I think a good way to analyze the results would be by converting to a `DataFrame` from the `DataFrames.jl` package. I added an example to the README for how to convert to a `DataFrame`. From there, it should be easy to compare across DataFrames for different parameters and measurements.

**Comment by mtfishman** [comment]
I thought about this more and decided I liked the suggestion of using `Observer([err_from_π, iteration])`. I don't think it needs a macro. The way I implemented it in #6 is that when a function is passed, the key in the Observer is the string representation of the function (Julia's internal representation of the function name). The string may be complicated for anonymous functions, but that is ok and we should just discourage people from passing anonymous functions to an `Observer` without specifying a name explicitly.
